%
% covid19_hessp.m
%
% This MATLAB function computes the derivatives of the vector field
% defined in covid19_vf.m.
%
% hessp_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th variable
% and the j-th parameter.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 19-Apr-2020 at 14:39
%
%
function hessp_ = covid19_hessp(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    StockholmPopulation = 2377081;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    r0         = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    qq         = p_(7);
    g          = p_(8);
    r0_dist    = p_(9);
    h          = p_(10);
    distancing_on = p_(11);
    Susceptible_ConservedConst = p_(12);

    hessp_ = zeros(5,5,12);

    hessp_(1,1,1) = l*Infectious*(-1+distancing_on);
    hessp_(1,1,2) = -1;
    hessp_(1,1,4) = Infectious*(r0*(-1+distancing_on)-distancing_on*r0_dist);
    hessp_(1,1,9) = -l*distancing_on*Infectious;
    hessp_(1,1,11) = -Infectious*(l*r0_dist-l*r0);
    hessp_(1,2,1) = l*(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit)*(-1+distancing_on)+l*Infectious*(-1+distancing_on);
    hessp_(1,2,4) = Infectious*(r0*(-1+distancing_on)-distancing_on*r0_dist)+(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit)*(r0*(-1+distancing_on)-distancing_on*r0_dist);
    hessp_(1,2,9) = -l*distancing_on*Infectious-l*distancing_on*(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit);
    hessp_(1,2,11) = -Infectious*(l*r0_dist-l*r0)-(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit)*(l*r0_dist-l*r0);
    hessp_(1,2,12) = -l*r0*(-1+distancing_on)+l*distancing_on*r0_dist;
    hessp_(1,3,1) = l*Infectious*(-1+distancing_on);
    hessp_(1,3,4) = Infectious*(r0*(-1+distancing_on)-distancing_on*r0_dist);
    hessp_(1,3,9) = -l*distancing_on*Infectious;
    hessp_(1,3,11) = -Infectious*(l*r0_dist-l*r0);
    hessp_(1,4,1) = l*Infectious*(-1+distancing_on);
    hessp_(1,4,4) = Infectious*(r0*(-1+distancing_on)-distancing_on*r0_dist);
    hessp_(1,4,9) = -l*distancing_on*Infectious;
    hessp_(1,4,11) = -Infectious*(l*r0_dist-l*r0);
    hessp_(1,5,1) = l*Infectious*(-1+distancing_on);
    hessp_(1,5,4) = Infectious*(r0*(-1+distancing_on)-distancing_on*r0_dist);
    hessp_(1,5,9) = -l*distancing_on*Infectious;
    hessp_(1,5,11) = -Infectious*(l*r0_dist-l*r0);

    hessp_(2,1,2) = 1;
    hessp_(2,2,3) = -1;
    hessp_(2,2,4) = -1;
    hessp_(2,2,7) = -1;

    hessp_(3,2,3) = 1;
    hessp_(3,3,5) = -1;
    hessp_(3,3,6) = -1;

    hessp_(4,2,4) = 1;
    hessp_(4,3,5) = 1;

    hessp_(5,2,7) = 1;
    hessp_(5,3,6) = 1;

