%
% covid19_der3.m
%
% This MATLAB function computes the third derivatives of the vector field
% defined in covid19_vf.m.
%
% der3_(n,i,j,k) is the third partial derivative of the n-th component
% of the vector field, taken with respect to the i-th, j-th and k-th variables.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on  3-Apr-2020 at 17:55
%
%
function der3_ = covid19_der3(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    r0         = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    r0_dist    = p_(8);
    distancing_on = p_(9);
    Susceptible_ConservedConst = p_(10);

    der3_ = zeros(5,5,5,5);






