%
% covid19_jac.m
%
% This MATLAB function computes the Jacobian of the vector field
% defined in covid19_vf.m.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on  3-Apr-2020 at 17:55
%
%
function jac_ = covid19_jac(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    r0         = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    r0_dist    = p_(8);
    distancing_on = p_(9);
    Susceptible_ConservedConst = p_(10);
    jac_ = zeros(5,5);
    jac_(1,1) = ((-1+distancing_on)*l*r0-r0_dist*distancing_on*l)*Infectious-a;
    jac_(1,2) = ((-1+distancing_on)*l*r0-r0_dist*distancing_on*l)*Infectious+((-1+distancing_on)*l*r0-r0_dist*distancing_on*l)*(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit);
    jac_(1,3) = ((-1+distancing_on)*l*r0-r0_dist*distancing_on*l)*Infectious;
    jac_(1,4) = ((-1+distancing_on)*l*r0-r0_dist*distancing_on*l)*Infectious;
    jac_(1,5) = ((-1+distancing_on)*l*r0-r0_dist*distancing_on*l)*Infectious;
    jac_(2,1) = a;
    jac_(2,2) = -c-l;
    jac_(3,2) = c;
    jac_(3,3) = -m-q;
    jac_(4,2) = l;
    jac_(4,3) = m;
    jac_(5,3) = q;

