%
% covid19_jacp.m
%
% This MATLAB function computes the Jacobian with respect to the parameters
% of the vector field defined in covid19_vf.m.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 28-Mar-2020 at 16:46
%
%
function jacp_ = covid19_jacp(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    Susceptible_ConservedConst = p_(8);
    jacp_ = zeros(5,8);
    jacp_(1,1) = -(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit)*Infectious;
    jacp_(1,2) = -Exposed;
    jacp_(1,8) = b*Infectious;
    jacp_(2,2) = Exposed;
    jacp_(2,3) = -Infectious;
    jacp_(2,4) = -Infectious;
    jacp_(2,7) = 1/8*Population^(-1)*Pi^(-1/2)*sqrt(2)*(-(0.0625)*g-(0.0625)*t)*exp(-(0.03125)*(g+t)^2);
    jacp_(3,3) = Infectious;
    jacp_(3,5) = -Krit;
    jacp_(3,6) = -Krit;
    jacp_(4,4) = Infectious;
    jacp_(4,5) = Krit;
    jacp_(5,6) = Krit;

