%
% covid19_Susceptible_mon.m
%
% MATLAB user function for the vector field: covid19
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on  3-Apr-2020 at 17:55
%
%
function r_ = covid19_Susceptible_mon(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    r0         = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    r0_dist    = p_(8);
    distancing_on = p_(9);
    Susceptible_ConservedConst = p_(10);
    Susceptible = -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit;
    sigma = 4;
    mu = -g;
    DIFF = sigma^(-1)*(t-mu);
    DIFFSQ = DIFF^2;
    EDIFFSQ = exp(-(0.5)*DIFFSQ);
    NORM = sigma*sqrt(Pi)*sqrt(2);
    Gaussian = EDIFFSQ*NORM^(-1);
    b = l*r0;
    b_dist = r0_dist*l;
    B = -b*(-1+distancing_on)+distancing_on*b_dist;
    infection = Infectious*Susceptible*B;
    outbreak = a*Exposed;
    critical = c*Infectious;
    quick_recovery = Infectious*l;
    late_recovery = m*Krit;
    death = q*Krit;
    initial_infection = Gaussian*Population^(-1);
    r_ = Susceptible;
