%
% covid19_jac.m
%
% This MATLAB function computes the Jacobian of the vector field
% defined in covid19_vf.m.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 25-Mar-2020 at 22:02
%
%
function jac_ = covid19_jac(t,x_,p_)
    Exposed    = x_(1);
    Infectious = x_(2);
    K          = x_(3);
    Recovered  = x_(4);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    Susceptible_ConservedConst = p_(6);
    jac_ = zeros(4,4);
    jac_(1,1) = -a-Infectious*b;
    jac_(1,2) = -(Recovered+Exposed+Infectious-Susceptible_ConservedConst+K)*b-Infectious*b;
    jac_(1,3) = -Infectious*b;
    jac_(1,4) = -Infectious*b;
    jac_(2,1) = a;
    jac_(2,2) = -c-l;
    jac_(3,2) = c;
    jac_(3,3) = -m;
    jac_(4,2) = l;
    jac_(4,3) = m;

