%
% covid19_hess.m
%
% This MATLAB function computes the Hessians of the vector field
% defined in covid19_vf.m.
%
% hess_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th and j-th variables.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on  3-Apr-2020 at 17:55
%
%
function hess_ = covid19_hess(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    r0         = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    r0_dist    = p_(8);
    distancing_on = p_(9);
    Susceptible_ConservedConst = p_(10);

    hess_ = zeros(5,5,5);

    hess_(1,1,2) = (-1+distancing_on)*l*r0-r0_dist*distancing_on*l;
    hess_(1,2,1) = hess_(1,1,2);
    hess_(1,2,2) = 2*(-1+distancing_on)*l*r0-2*r0_dist*distancing_on*l;
    hess_(1,2,3) = (-1+distancing_on)*l*r0-r0_dist*distancing_on*l;
    hess_(1,3,2) = hess_(1,2,3);
    hess_(1,2,4) = (-1+distancing_on)*l*r0-r0_dist*distancing_on*l;
    hess_(1,4,2) = hess_(1,2,4);
    hess_(1,2,5) = (-1+distancing_on)*l*r0-r0_dist*distancing_on*l;
    hess_(1,5,2) = hess_(1,2,5);





