%
% covid19_hess.m
%
% This MATLAB function computes the Hessians of the vector field
% defined in covid19_vf.m.
%
% hess_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th and j-th variables.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 25-Mar-2020 at 22:02
%
%
function hess_ = covid19_hess(t,x_,p_)
    Exposed    = x_(1);
    Infectious = x_(2);
    K          = x_(3);
    Recovered  = x_(4);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    Susceptible_ConservedConst = p_(6);

    hess_ = zeros(4,4,4);

    hess_(1,1,2) = -b;
    hess_(1,2,1) = hess_(1,1,2);
    hess_(1,2,2) = -2*b;
    hess_(1,2,3) = -b;
    hess_(1,3,2) = hess_(1,2,3);
    hess_(1,2,4) = -b;
    hess_(1,4,2) = hess_(1,2,4);




