%
% covid19_der3.m
%
% This MATLAB function computes the third derivatives of the vector field
% defined in covid19_vf.m.
%
% der3_(n,i,j,k) is the third partial derivative of the n-th component
% of the vector field, taken with respect to the i-th, j-th and k-th variables.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 27-Mar-2020 at 15:03
%
%
function der3_ = covid19_der3(t,x_,p_)
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    Susceptible_ConservedConst = p_(7);

    der3_ = zeros(5,5,5,5);






