%
% covid19_jacp.m
%
% This MATLAB function computes the Jacobian with respect to the parameters
% of the vector field defined in covid19_vf.m.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 26-Mar-2020 at 10:05
%
%
function jacp_ = covid19_jacp(t,x_,p_)
    Exposed    = x_(1);
    Infectious = x_(2);
    K          = x_(3);
    Recovered  = x_(4);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    Susceptible_ConservedConst = p_(6);
    jacp_ = zeros(4,6);
    jacp_(1,1) = -(Recovered+Exposed+Infectious-Susceptible_ConservedConst+K)*Infectious;
    jacp_(1,2) = -Exposed;
    jacp_(1,6) = b*Infectious;
    jacp_(2,2) = Exposed;
    jacp_(2,3) = -Infectious;
    jacp_(2,4) = -Infectious;
    jacp_(3,3) = Infectious;
    jacp_(3,5) = -K;
    jacp_(4,4) = Infectious;
    jacp_(4,5) = K;

