%
% covid19_jac.m
%
% This MATLAB function computes the Jacobian of the vector field
% defined in covid19_vf.m.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 28-Mar-2020 at 16:46
%
%
function jac_ = covid19_jac(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    Susceptible_ConservedConst = p_(8);
    jac_ = zeros(5,5);
    jac_(1,1) = -a-b*Infectious;
    jac_(1,2) = -b*(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit)-b*Infectious;
    jac_(1,3) = -b*Infectious;
    jac_(1,4) = -b*Infectious;
    jac_(1,5) = -b*Infectious;
    jac_(2,1) = a;
    jac_(2,2) = -c-l;
    jac_(3,2) = c;
    jac_(3,3) = -m-q;
    jac_(4,2) = l;
    jac_(4,3) = m;
    jac_(5,3) = q;

