%
% covid19_Susceptible_mon.m
%
% MATLAB user function for the vector field: covid19
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 27-Mar-2020 at 15:03
%
%
function r_ = covid19_Susceptible_mon(t,x_,p_)
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    Susceptible_ConservedConst = p_(7);
    Susceptible = Susceptible_ConservedConst-Krit-Recovered-Exposed-Dead-Infectious;
    infection = b*Susceptible*Infectious;
    outbreak = a*Exposed;
    critical = c*Infectious;
    quick_recovery = l*Infectious;
    late_recovery = Krit*m;
    death = Krit*q;
    r_ = Susceptible;
