%
% covid19_hess.m
%
% This MATLAB function computes the Hessians of the vector field
% defined in covid19_vf.m.
%
% hess_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th and j-th variables.
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 28-Mar-2020 at 16:46
%
%
function hess_ = covid19_hess(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    Susceptible_ConservedConst = p_(8);

    hess_ = zeros(5,5,5);

    hess_(1,1,2) = -b;
    hess_(1,2,1) = hess_(1,1,2);
    hess_(1,2,2) = -2*b;
    hess_(1,2,3) = -b;
    hess_(1,3,2) = hess_(1,2,3);
    hess_(1,2,4) = -b;
    hess_(1,4,2) = hess_(1,2,4);
    hess_(1,2,5) = -b;
    hess_(1,5,2) = hess_(1,2,5);





