%
% covid19_Recovered_underestimate.m
%
% MATLAB user function for the vector field: covid19
%
% This file was generated by the program VFGEN, version: 2.6.0.dev1
% Generated on 28-Mar-2020 at 16:46
%
%
function r_ = covid19_Recovered_underestimate(t,x_,p_)
    Pi = pi;
    Population = 10120000;
    Exposed    = x_(1);
    Infectious = x_(2);
    Krit       = x_(3);
    Recovered  = x_(4);
    Dead       = x_(5);
    b          = p_(1);
    a          = p_(2);
    c          = p_(3);
    l          = p_(4);
    m          = p_(5);
    q          = p_(6);
    g          = p_(7);
    Susceptible_ConservedConst = p_(8);
    Susceptible = -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit;
    sigma = 4;
    mu = -g;
    DIFF = -sigma^(-1)*(mu-t);
    DIFFSQ = DIFF^2;
    EDIFFSQ = exp(-(0.5)*DIFFSQ);
    NORM = sigma*sqrt(Pi)*sqrt(2);
    Gaussian = EDIFFSQ*NORM^(-1);
    infection = b*Infectious*Susceptible;
    outbreak = Exposed*a;
    critical = c*Infectious;
    quick_recovery = l*Infectious;
    late_recovery = m*Krit;
    death = Krit*q;
    initial_infection = Population^(-1)*Gaussian;
    r_ = Recovered;
