#
# covid19.py
#
# Python file for the vector field named: covid19
#

"""
This module implements the vector field name "covid19" as
the function vectorfield().  The Jacobian of the vector field
is computed by jacobian().  These functions can be used with
the SciPy odeint function.

For example:

    from scipy.integrate import odeint
    import covid19

    params = [r0, a, c, l, m, q, g, r0_dist, distancing_on, Susceptible_ConservedConst]   # Assume the parameters have been set elsewhere
    t = [i/10.0 for i in range(0, 101)]
    ic = [1.0,0.0,0.0,0.0,0.0]
    sol = odeint(covid19.vectorfield, ic, t, args=(params,), Dfun=covid19.jacobian)

This file was generated by the program VFGEN, version: 2.6.0.dev1
Generated on  6-Apr-2020 at 00:17

"""

from math import *
import numpy

#
# The vector field.
#

def vectorfield(y_, t_, p):
    """
    The vector field function for the vector field "covid19"
    Arguments:
        y_ :  vector of the state variables:
                  y_[0] is Exposed
                  y_[1] is Infectious
                  y_[2] is Krit
                  y_[3] is Recovered
                  y_[4] is Dead
        t_ :  time
        p_ :  vector of the parameters
                  p_[0] is r0
                  p_[1] is a
                  p_[2] is c
                  p_[3] is l
                  p_[4] is m
                  p_[5] is q
                  p_[6] is g
                  p_[7] is r0_dist
                  p_[8] is distancing_on
                  p_[9] is Susceptible_ConservedConst
    """
    Pi = pi
    Population = 10120000.0
    Exposed    = y_[0]
    Infectious = y_[1]
    Krit       = y_[2]
    Recovered  = y_[3]
    Dead       = y_[4]

    r0         = p_[0]
    a          = p_[1]
    c          = p_[2]
    l          = p_[3]
    m          = p_[4]
    q          = p_[5]
    g          = p_[6]
    r0_dist    = p_[7]
    distancing_on = p_[8]
    Susceptible_ConservedConst = p_[9]

    Susceptible =  Susceptible_ConservedConst-Krit-Recovered-Exposed-Dead-Infectious
    sigma = 4.0
    mu = -g
    DIFF = 1.0/sigma*( t-mu)
    DIFFSQ = (DIFF*DIFF)
    EDIFFSQ = exp(-5.0000000000000000e-01*DIFFSQ)
    NORM = pow(2.0,(1.0/2.0))*pow(Pi,(1.0/2.0))*sigma
    Gaussian = 1.0/NORM*EDIFFSQ
    b = l*r0
    b_dist = l*r0_dist
    B =  distancing_on*b_dist-( distancing_on-1.0)*b
    infection = Susceptible*B*Infectious
    outbreak = a*Exposed
    critical = c*Infectious
    quick_recovery = l*Infectious
    late_recovery = Krit*m
    death = Krit*q
    initial_infection = Gaussian/Population

    f_ = numpy.zeros((5,))
    f_[0] =  infection-outbreak
    f_[1] = -critical+initial_infection-quick_recovery+outbreak
    f_[2] = -death+critical-late_recovery
    f_[3] =  quick_recovery+late_recovery
    f_[4] = death

    return f_

#
#  The Jacobian.
#

def jacobian(y_, t_, p_):
    """
    The Jacobian of the vector field "covid19"
    Arguments:
        y_ :  vector of the state variables:
                  y_[0] is Exposed
                  y_[1] is Infectious
                  y_[2] is Krit
                  y_[3] is Recovered
                  y_[4] is Dead
        t_ :  time
        p_ :  vector of the parameters
                  p_[0] is r0
                  p_[1] is a
                  p_[2] is c
                  p_[3] is l
                  p_[4] is m
                  p_[5] is q
                  p_[6] is g
                  p_[7] is r0_dist
                  p_[8] is distancing_on
                  p_[9] is Susceptible_ConservedConst
    """
    Pi = pi
    Population = 10120000.0
    Exposed    = y_[0]
    Infectious = y_[1]
    Krit       = y_[2]
    Recovered  = y_[3]
    Dead       = y_[4]
    r0         = p_[0]
    a          = p_[1]
    c          = p_[2]
    l          = p_[3]
    m          = p_[4]
    q          = p_[5]
    g          = p_[6]
    r0_dist    = p_[7]
    distancing_on = p_[8]
    Susceptible_ConservedConst = p_[9]

    # Create the Jacobian matrix:
    jac_ = numpy.zeros((5,5))
    jac_[0,0] = -a-( l*r0_dist*distancing_on-l*r0*( distancing_on-1.0))*Infectious
    jac_[0,1] =  ( Susceptible_ConservedConst-Krit-Recovered-Exposed-Dead-Infectious)*( l*r0_dist*distancing_on-l*r0*( distancing_on-1.0))-( l*r0_dist*distancing_on-l*r0*( distancing_on-1.0))*Infectious
    jac_[0,2] = -( l*r0_dist*distancing_on-l*r0*( distancing_on-1.0))*Infectious
    jac_[0,3] = -( l*r0_dist*distancing_on-l*r0*( distancing_on-1.0))*Infectious
    jac_[0,4] = -( l*r0_dist*distancing_on-l*r0*( distancing_on-1.0))*Infectious
    jac_[1,0] = a
    jac_[1,1] = -l-c
    jac_[2,1] = c
    jac_[2,2] = -m-q
    jac_[3,1] = l
    jac_[3,2] = m
    jac_[4,2] = q
    return jac_

