#
# covid19.R
#
# R vector field functions for: covid19
#
# This file was generated by the program VFGEN, version: 2.6.0.dev0
# Generated on 31-Aug-2020 at 15:37
#


#
# covid19(t, state, parameters)
#
# The vector field function
#
covid19 <- function(t, state, parameters) {
    Pi <- pi
        Population <- 10120000
        StockholmPopulation <- 2377081
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]

    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit;
    sigma <- 4;
    mu <- -g;
    DIFF <- sigma^(-1)*(t-mu);
    DIFFSQ <- DIFF^2;
    EDIFFSQ <- exp(-(0.5)*DIFFSQ);
    NORM <- sigma*sqrt(2)*sqrt(Pi);
    Gaussian <- EDIFFSQ*NORM^(-1);
    b <- l*r0;
    b_dist <- l*r0_dist;
    B <- -b*(-1+distancing_on)+distancing_on*b_dist;
    infection <- B*Infectious*Susceptible;
    outbreak <- Exposed*a;
    critical <- Infectious*c;
    quick_recovery <- l*Infectious;
    late_recovery <- m*Krit;
    critical_death <- q*Krit;
    infectious_death <- qq*Infectious;
    initial_infection <- Gaussian*Population^(-1);
    vf_ <- vector(len = 5)
    vf_[1] = infection-outbreak;
    vf_[2] = -critical-infectious_death-quick_recovery+initial_infection+outbreak;
    vf_[3] = -critical_death+critical-late_recovery;
    vf_[4] = quick_recovery+late_recovery;
    vf_[5] = critical_death+infectious_death;
    return(list(vf_))
}

#
# covid19_jac(t, state, parameters)
#
# The jacobian function
#
covid19_jac <- function(t, state, parameters) {
    Pi <- pi;
    Population = 10120000;
    StockholmPopulation = 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    jac_ = matrix(nrow = 5, ncol = 5)
    jac_[1,1] = (l*r0*(-1+distancing_on)-l*distancing_on*r0_dist)*Infectious-a
    jac_[1,2] = (l*r0*(-1+distancing_on)-l*distancing_on*r0_dist)*(Recovered+Exposed+Dead+Infectious-Susceptible_ConservedConst+Krit)+(l*r0*(-1+distancing_on)-l*distancing_on*r0_dist)*Infectious
    jac_[1,3] = (l*r0*(-1+distancing_on)-l*distancing_on*r0_dist)*Infectious
    jac_[1,4] = (l*r0*(-1+distancing_on)-l*distancing_on*r0_dist)*Infectious
    jac_[1,5] = (l*r0*(-1+distancing_on)-l*distancing_on*r0_dist)*Infectious
    jac_[2,1] = a
    jac_[2,2] = -qq-l-c
    jac_[2,3] = 0
    jac_[2,4] = 0
    jac_[2,5] = 0
    jac_[3,1] = 0
    jac_[3,2] = c
    jac_[3,3] = -m-q
    jac_[3,4] = 0
    jac_[3,5] = 0
    jac_[4,1] = 0
    jac_[4,2] = l
    jac_[4,3] = m
    jac_[4,4] = 0
    jac_[4,5] = 0
    jac_[5,1] = 0
    jac_[5,2] = qq
    jac_[5,3] = q
    jac_[5,4] = 0
    jac_[5,5] = 0
    return(jac_)
}


#
# covid19_sol_Susceptible_mon
#
# This function implements the user-defined function "Susceptible_mon"
#
covid19_sol_Susceptible_mon <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Susceptible;
    return(r_)
}

#
# covid19_Susceptible_mon
#
# This function implements the user-defined function "Susceptible_mon"
#
covid19_Susceptible_mon <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Susceptible;
    return(r_)
}

#
# covid19_sol_Infectious_underestimate
#
# This function implements the user-defined function "Infectious_underestimate"
#
covid19_sol_Infectious_underestimate <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Infectious;
    return(r_)
}

#
# covid19_Infectious_underestimate
#
# This function implements the user-defined function "Infectious_underestimate"
#
covid19_Infectious_underestimate <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Infectious;
    return(r_)
}

#
# covid19_sol_Recovered_underestimate
#
# This function implements the user-defined function "Recovered_underestimate"
#
covid19_sol_Recovered_underestimate <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Recovered;
    return(r_)
}

#
# covid19_Recovered_underestimate
#
# This function implements the user-defined function "Recovered_underestimate"
#
covid19_Recovered_underestimate <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Recovered;
    return(r_)
}

#
# covid19_sol_Deaths_recorded
#
# This function implements the user-defined function "Deaths_recorded"
#
covid19_sol_Deaths_recorded <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Dead;
    return(r_)
}

#
# covid19_Deaths_recorded
#
# This function implements the user-defined function "Deaths_recorded"
#
covid19_Deaths_recorded <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Dead;
    return(r_)
}

#
# covid19_sol_Critically_sick
#
# This function implements the user-defined function "Critically_sick"
#
covid19_sol_Critically_sick <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Krit;
    return(r_)
}

#
# covid19_Critically_sick
#
# This function implements the user-defined function "Critically_sick"
#
covid19_Critically_sick <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- Krit;
    return(r_)
}

#
# covid19_sol_inequality_constraint_recovery
#
# This function implements the user-defined function "inequality_constraint_recovery"
#
covid19_sol_inequality_constraint_recovery <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- (1+exp(-(5.0)*l+(5.0)*m))^(-1);
    return(r_)
}

#
# covid19_inequality_constraint_recovery
#
# This function implements the user-defined function "inequality_constraint_recovery"
#
covid19_inequality_constraint_recovery <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- (1+exp(-(5.0)*l+(5.0)*m))^(-1);
    return(r_)
}

#
# covid19_sol_inequality_constraint_infection
#
# This function implements the user-defined function "inequality_constraint_infection"
#
covid19_sol_inequality_constraint_infection <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- (1+exp(-(5.0)*r0+(5.0)*r0_dist))^(-1);
    return(r_)
}

#
# covid19_inequality_constraint_infection
#
# This function implements the user-defined function "inequality_constraint_infection"
#
covid19_inequality_constraint_infection <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- (1+exp(-(5.0)*r0+(5.0)*r0_dist))^(-1);
    return(r_)
}

#
# covid19_sol_hospital_beds
#
# This function implements the user-defined function "hospital_beds"
#
covid19_sol_hospital_beds <- function(sol, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    t <- sol[, 1]
    Exposed    <- sol[, 2]
    Infectious <- sol[, 3]
    Krit       <- sol[, 4]
    Recovered  <- sol[, 5]
    Dead       <- sol[, 6]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- h*Infectious;
    return(r_)
}

#
# covid19_hospital_beds
#
# This function implements the user-defined function "hospital_beds"
#
covid19_hospital_beds <- function(t, state, parameters) {
    Pi <- pi;
    Population <- 10120000;
    StockholmPopulation <- 2377081;
    Exposed    <- state[1]
    Infectious <- state[2]
    Krit       <- state[3]
    Recovered  <- state[4]
    Dead       <- state[5]
    r0         <- parameters[1]
    a          <- parameters[2]
    c          <- parameters[3]
    l          <- parameters[4]
    m          <- parameters[5]
    q          <- parameters[6]
    qq         <- parameters[7]
    g          <- parameters[8]
    r0_dist    <- parameters[9]
    h          <- parameters[10]
    distancing_on <- parameters[11]
    Susceptible_ConservedConst <- parameters[12]
    Susceptible <- -Recovered-Exposed-Dead-Infectious+Susceptible_ConservedConst-Krit
    sigma <- 4
    mu <- -g
    DIFF <- sigma^(-1)*(t-mu)
    DIFFSQ <- DIFF^2
    EDIFFSQ <- exp(-(0.5)*DIFFSQ)
    NORM <- sigma*sqrt(2)*sqrt(Pi)
    Gaussian <- EDIFFSQ*NORM^(-1)
    b <- l*r0
    b_dist <- l*r0_dist
    B <- -b*(-1+distancing_on)+distancing_on*b_dist
    infection <- B*Infectious*Susceptible
    outbreak <- Exposed*a
    critical <- Infectious*c
    quick_recovery <- l*Infectious
    late_recovery <- m*Krit
    critical_death <- q*Krit
    infectious_death <- qq*Infectious
    initial_infection <- Gaussian*Population^(-1)
    r_ <- h*Infectious;
    return(r_)
}
